### ISSUE TITLE
Big5 encoding/decoding support

### ISSUE THREAD

**Issue by r12a** [whatwg/encoding#58] opened 2016-06-20 15:43 UTC
Results for a series of tests for Big5 encoding/decoding can be found at 
https://www.w3.org/International/tests/repo/results/encoding-dbl-byte.en#big5

The tests can be run from that page (select the link in the left-most column) or get the tests from the WPT repo.  There is a PR at
https://github.com/w3c/web-platform-tests/pull/3197

The tests check whether:
1. the browser produces the expected byte sequences for all characters in the big5 encoding after 0x9F when encoding bytes for a URL produced by a form, using the encoder steps in the specification.
2. the browser produces percent-escaped character references for a URL produced by a form when encoding miscellaneous characters that are not in the big5 encoding. (tests for several ranges)
3. same two types of test when writing characters to an href value
4. the browser decodes all characters as expected from a file generated by encoding all pointers in the big5 encoding per the encoder steps in the specification.
5. the browser decodes all characters as expected from a file generated by encoding all pointers less than 5024 in the big5 encoding per the encoder steps in the specification.
6. the browser decodes characters that are not recognised from the big5 encoding as replacement characters.

The following summarises the current situation according to my testing, for major desktop browsers.  (I will be adding nightly results and perhaps other browsers in time.)  The table lists the number of characters that were NOT successfully converted by the test.

![screen shot 2016-06-20 at 16 26 04](https://cloud.githubusercontent.com/assets/4839211/16200559/c35090dc-3705-11e6-998d-cc67d8b84c13.png)

Notes:
- Edge fails all href encode tests because characters are not converted to percent-escapes in the href attribute.
- Firefox fails all href encode tests for characters not in the encoding because it converts characters to percent-escaped Unicode values instead.

Can we please investigate the failures to ascertain whether:
1. the browser needs to be changed
2. the spec needs to be changed
3. the test is at fault

The following tool may be helpful for investigating issues. It converts between byte sequences and characters for all encodings in the Encoding spec. http://r12a.github.io/apps/encodings/

**Comment by r12a** [comment] 2016-09-15 17:12
List of bugs raised:

- https://bugs.webkit.org/show_bug.cgi?id=159890
- https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8202219/

**Comment by r12a** [comment] 2016-09-15 17:13
List of bugs raised:

- https://bugs.webkit.org/show_bug.cgi?id=159891
- https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8202252/

**Comment by jungshik** [comment] 2016-09-16 06:02
Again, in case of Chromium's form(misc) failures,  it has the same root cause as #62, #59, #61: See 
https://bugs.chromium.org/p/chromium/issues/detail?id=647568

**Comment by r12a** [comment] 2017-06-15 07:39
Today and yesterday i updated the results at https://www.w3.org/International/tests/repo/results/encoding-dbl-byte.en#big5 for Firefox, FNightly, Chrome, and Canary. The latest summary is:

![screen shot 2017-06-15 at 08 38 54](https://user-images.githubusercontent.com/4839211/27170535-27854cbc-51a6-11e7-91b0-fbb8ef2b270d.png)

**Comment by hsivonen** [comment] 2017-06-15 09:28
Thank you. The Big5 tests LGTM for merging into WPT. /cc @domenic

**Comment by domenic** [comment] 2017-06-15 21:56
Let's close this as https://github.com/w3c/web-platform-tests/pull/6254 is ready to merge.

**Comment by domenic** [comment] 2017-06-16 14:38
Reopening per https://github.com/whatwg/encoding/issues/61#issuecomment-309043248

**Comment by annevk** [comment] 2018-10-17 07:50
Now that Firefox passes all these tests and a year has passed, I'm happy to consider this done. A new issue would also be less noisy at this point, were one warranted.

**Closed by annevk** 2018-10-17 07:50 UTC
Labels: tests
